name: AI Jain Video Factory

on:
  push:
    paths:
      - "stories/**"

jobs:
  build-video:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install ffmpeg
      run: sudo apt-get install ffmpeg -y

    - name: Install libs
      run: pip install -r requirements.txt

    - name: Generate AI Video
      run: python generate_video.py
      env:
        ELEVENLABS_API_KEY: ${{ secrets.ELEVENLABS_API_KEY }}
        HF_API_KEY: ${{ secrets.HF_API_KEY }}
        YOUTUBE_CLIENT_ID: ${{ secrets.YOUTUBE_CLIENT_ID }}
        YOUTUBE_CLIENT_SECRET: ${{ secrets.YOUTUBE_CLIENT_SECRET }}
        YOUTUBE_REFRESH_TOKEN: ${{ secrets.YOUTUBE_REFRESH_TOKEN }}
